# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20170417_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='age',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='location',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='principal',
            new_name='position',
        ),
    ]
