# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20170501_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager')], max_length=256),
        ),
    ]
