# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='depname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depatments', to='basic_app.Department'),
        ),
    ]
