# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_employee_depname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
