# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep',
            field=models.CharField(max_length=256),
        ),
    ]
