# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20170525_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='namedep',
            field=models.CharField(default='x', max_length=256),
            preserve_default=False,
        ),
    ]
