# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_department_namedep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('worker', 'Worker')], max_length=256),
        ),
    ]
