# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
