# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_attendance_attendance_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_pic',
            field=models.ImageField(null=True, upload_to='attendance_pic'),
        ),
    ]
