# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_auto_20170529_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='xx',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_pic',
            field=models.ImageField(null=True, upload_to='attendance_pics'),
        ),
    ]
