# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_attendance_attendance_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depatments', to='basic_app.Department'),
        ),
    ]
