# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_auto_20170530_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='xx',
        ),
    ]
