# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0029_remove_attendance_xx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('worker', 'Worker')], max_length=256),
        ),
    ]
