# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0031_auto_20170531_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('worker', 'Worker')], default='Position', max_length=256),
        ),
    ]
