# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_auto_20170531_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depname',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depatments', to='basic_app.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('worker', 'Worker')], default='', max_length=256),
        ),
    ]
