# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0033_auto_20170531_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depname',
            field=models.ForeignKey(blank=True, default='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depatments', to='basic_app.Department'),
        ),
    ]
