# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0035_auto_20170531_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='namedep',
        ),
    ]
